ボウリングのスコア計算プログラムオブジェクト指向版の課題
obregonia1/ruby-practices pull request #12
Opened 2021-03-29 12:56 UTC by obregonia1

確認よろしくお願いします。

2021-04-04 02:47 UTC, u1tnk requested changes

2021-04-04 02:47 UTC, u1tnk commented on 07.bowling_object/bowling_oop.rb
> +  attr_reader :frames
外部から参照されないときは attr_readerではなく インスタンス変数のまま使う方が良いですね。
見える必要の無いところでは見えないようにした方が影響範囲が狭くなるので。

2021-04-04 02:47 UTC, u1tnk commented on 07.bowling_object/bowling_oop.rb
> +          create_frame_obj(frame_num, frame_shots, @frames)
`_obj` は無くて良い気がします。

2021-04-04 02:47 UTC, u1tnk commented on 07.bowling_object/bowling_oop.rb
> +  def create_frame_obj(frame_num, frame_shots, frames)
同じインスタンス内なので framesを引数に渡す必要は無いと思います。

2021-04-04 02:47 UTC, u1tnk commented on 07.bowling_object/bowling_oop.rb
> +      if strike_frame.frame_num != 9 && strike_next_frame.strike?
`strike_frame.frame_num != 9` この意味がちょっと分かりませんでした。 strike_frameなので10なのでは？

2021-04-04 08:00 UTC, obregonia1 commented on 07.bowling_object/bowling_oop.rb
> +  attr_reader :frames
なるほど！
なんとなく`attr_reader`書かなければと考えていたので、確かに不要ですね！

2021-04-04 08:34 UTC, obregonia1 commented on 07.bowling_object/bowling_oop.rb
> +      if strike_frame.frame_num != 9 && strike_next_frame.strike?
`strike_frame`のフレーム数が9ではないという意味ですね！
1〜8フレームでダブルが出たときの条件分岐です。

2021-04-05 02:27 UTC, u1tnk commented on 07.bowling_object/bowling_oop.rb
> +      if strike_frame.frame_num != 9 && strike_next_frame.strike?
なるほど。点数じゃなくてフレームの順番という事か。
細かいし、私が勘違いしたからというのもありますが、`num`は抽象的なので、`index`、`point`等にすると勘違いしづらいかもしれませんね。

2021-04-05 02:28 UTC, u1tnk approved these changes

2021-04-05 04:18 UTC, obregonia1 commented on 07.bowling_object/bowling_oop.rb
> +      if strike_frame.frame_num != 9 && strike_next_frame.strike?
確かに`index`の方が分かりやすいですね！
変更しておきました。

2021-04-05 04:18 UTC, merged