lsコマンドを作るオブジェクト指向版の課題
obregonia1/ruby-practices pull request #13
Opened 2021-03-31 04:26 UTC by obregonia1

確認よろしくお願いします。

2021-04-07 05:26 UTC, komagata requested changes

2021-04-07 05:26 UTC, komagata commented on 08.ls_object/ls_object.rb
> +class MyFile
`MyFile`はなぜlsコマンドにこういう名前が出てくるのか他の人から見るとわからないかもです。

2021-04-07 05:26 UTC, komagata commented on 08.ls_object/ls_object.rb
> +class Exec
あまり名前を省略しない方がいいかもです。

[プログラミング初心者は変数名やメソッド名を略さない方がいいよ、という話 \- give IT a try](https://blog.jnito.com/entry/2020/10/20/092724)

またExecuteだと動詞になるので、クラス名は原則名刺なので考えてみてください〜

2021-04-08 01:54 UTC, obregonia1 commented on 08.ls_object/ls_object.rb
> +class MyFile
了解しました！
`Parameter`に変更しました。

2021-04-08 01:55 UTC, obregonia1 commented on 08.ls_object/ls_object.rb
> +class Exec
こちらも`Execution`に変更しました。

2021-04-08 04:58 UTC, komagata requested changes

2021-04-08 04:58 UTC, komagata commented on 08.ls_object/ls_object.rb
> +class Parameter
Parameterなどとても一般的な単語で他の名前とぶつかってしまうかもです。

このプログラムに共通のnamespaceをmoduleを使って導入するといいと思います。

下記のプラクティスの参考のいくつかのgemをみてみるとわかるかもです。gemの場合も一般的には共通のnamespaceを用意してその下にクラスを作ります。

[オブジェクト指向プログラミング \| FJORD BOOT CAMP（フィヨルドブートキャンプ）](https://bootcamp.fjord.jp/practices/211)

また、Parameterはプログラムではさまざまなパラメータがあり、何のParameterを指しているのかわからないのでもう少し具体的な名前にした方が良いかもです。

2021-04-08 04:58 UTC, komagata commented on 08.ls_object/ls_object.rb
> +class Execution
ほとんど全てのプログラムは**実行**するものなのでExecutionだとみる人に追加の情報を与えてないことになっちゃうので他の名前がいいかもです。

例えばコマンドラインから実行するタイプのコマンドを実装しているgemを色々みてみるとどういう名前をつけるのがいいのかわかるかもです〜

2021-04-09 06:47 UTC, obregonia1 commented on 08.ls_object/ls_object.rb
> +class Parameter
module`LS`を名前空間のため作成しクラス名を`File`に変更しました！

2021-04-09 06:58 UTC, obregonia1 commented on 08.ls_object/ls_object.rb
> +class Execution
なるほど、勉強になります！
クラス名を`CommandLine`メソッド名を`run`に変更しました。

2021-04-09 16:38 UTC, komagata requested changes

2021-04-09 16:38 UTC, komagata commented on 08.ls_object/ls_object.rb
> +class LS::File
基本的にはこういう書き方をしないです。

なぜかというと、基本的には1クラス1ファイルに書きます。
しかし`LS::File`が出現したときに`LS`moduleが未定義だとエラーになります。
ファイルの読み込む順番によってエラーが出ると不便なので下記のように書いた方がいいです。

```ruby
module LS
  class File
  end
end
```

2021-04-10 02:36 UTC, obregonia1 commented on 08.ls_object/ls_object.rb
> +class LS::File
元々の`File`クラスを使いたかったのでこういう書き方をしていた。。。
`LS::File`内での`File`を`::File`に変更すると対処できることがわかったので変更しました。

2021-04-10 05:48 UTC, komagata commented on 08.ls_object/ls_object.rb
> +class LS::File
モジュールを使ったことで、`File`などの一般的な名詞が使えるのはとってもいいことだと思います〜

2021-04-10 05:49 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-04-14 00:08 UTC, merged