lsコマンドのプログラム課題
obregonia1/ruby-practices pull request #7
Opened 2021-01-20 08:13 UTC by obregonia1

確認よろしくお願いします。

2021-01-24 05:25 UTC, torinoko requested changes
@obregonia1 
確認しました！
クラスやメソッドの依存が複雑になっていますね。
クラスを使わない形で一回書いてみてもいいかもしれませんね。

2021-01-24 05:25 UTC, torinoko commented on 05.ls/ls.rb
> +end
`module` を作っているのは何か理由がありますか？
`File` クラスが Ruby にすでにあるので、ネームスペースを分けるためかな？と思うのですが、もしそうであれば `class` の名前を変えてもいいかもしれないですね。
（今回はこのままでも大丈夫です）

2021-01-24 05:25 UTC, torinoko commented on 05.ls/ls.rb
> +        end
r, w, x の3種類のモードがあり、3列それぞれでどれかに該当する可能性があるので、この条件分岐ではカバーしきれないと思います（ `--r` とか `xxx` とかもあり得る）

2021-01-24 05:25 UTC, torinoko commented on 05.ls/ls.rb
> +        end
数値 `mode` を文字列 `mode_abc` に変えているのかな？と思いますが、もしそうであれば `abc` ではなくて `char` や `string` のような変数名の方がいいかもしれませんね。

2021-01-24 05:25 UTC, torinoko commented on 05.ls/ls.rb
> +    Dir.foreach('.').map { |f| f }
ここで改行して2行にしている理由はありますか？

2021-01-24 05:25 UTC, torinoko commented on 05.ls/ls.rb
> +    Dir.foreach('.').map { |f| f }
`.map { |f| f }` はどんな理由で追加していますか？

2021-01-24 05:25 UTC, torinoko commented on 05.ls/ls.rb
> +    file_names.map { |f| File.stat(f) }
ここも改行している理由があれば教えてください〜

2021-01-24 05:25 UTC, torinoko commented on 05.ls/ls.rb
> +  NAME_SIZE = FILES.map { |file| file.name.size }
`class` での大文字は定数定義に使います。
今回のようなケースでは適切ではないかなーと思います。
（FILES や HIDDEN_FILES も同様です）

2021-01-24 05:25 UTC, torinoko commented on 05.ls/ls.rb
> +class Exec < List::File
`List::File` を継承しているのはなぜでしょう？

2021-01-24 05:25 UTC, torinoko commented on 05.ls/ls.rb
> +end
`-a` オプションの場合がない？かな？
ここの条件、もう少しすっきり書けそうな気がしますね。
（ `Exec.long` や `Exec.display` が呼ばれている箇所が複数あるので）

2021-01-24 06:14 UTC, obregonia1 commented on 05.ls/ls.rb
> +  def initialize(type, permission, hard_link, owner, group, size, time)
属性は5個以上使わないようにとrubocopに指摘された点です。

2021-01-24 06:16 UTC, obregonia1 commented on 05.ls/ls.rb
> +  def self.display(files)
rubocopに複雑だと指摘された点ですが、こちらは修正してみます。

2021-01-24 06:25 UTC, obregonia1 commented on 05.ls/ls.rb
> +end
ネームスペースを分けるために作りました。

2021-01-24 06:40 UTC, obregonia1 commented on 05.ls/ls.rb
> +        end
これは`l`オプションの表示だと所有者、所有者グループ、その他のユーザの順に`-rw-r--r--`のように表示されるので`--r`や`xxx`は有りえないと思います。
`File::stat.mode`で取得した値`764` => `rwxrw-r--`のように変換しています。

2021-01-24 06:56 UTC, obregonia1 commented on 05.ls/ls.rb
> +    Dir.foreach('.').map { |f| f }
ここの改行は不要でした。
[るりま](https://docs.ruby-lang.org/ja/search/query:dir/query:foreach/)によると`Dir::foreach`はブロックを評価するという事なので、`{ |f| f }`を追加し`map`を追加して`file_names`という配列を作りました。

2021-01-24 07:39 UTC, torinoko reviewed
追加でコメントしました。
修正お待ちしてますね！

2021-01-24 07:39 UTC, torinoko commented on 05.ls/ls.rb
> +end
お返事ありがとうございます！なるほど！

2021-01-24 07:39 UTC, torinoko commented on 05.ls/ls.rb
> +  def initialize(type, permission, hard_link, owner, group, size, time)
あーなるほど！確かに指摘されちゃいますね。
だとすると何かしら対応を考えたいところですね。

- 数の多い引数をうまいこと渡す方法を考えてみる
- そもそもたくさんの引数が渡されるようなクラスの設計は合ってるか考えてみる

2021-01-24 07:39 UTC, torinoko commented on 05.ls/ls.rb
> +        end
あ！ごめんなさい！！！
権限ごとの表示ですね、私が読み間違えていました 🙏

2021-01-24 07:39 UTC, torinoko commented on 05.ls/ls.rb
> +    Dir.foreach('.').map { |f| f }
`.to_a` しても同じ結果が返るのでどうでしょう？
何もしない `#map` があると「なんだろう？」って思うので、別の方法を取れるときはその方がいいかもしれないですね。

2021-01-24 23:59 UTC, obregonia1 commented on 05.ls/ls.rb
> +    Dir.foreach('.').map { |f| f }
`to_a`を使った方がいいですね！
修正しました。

2021-01-25 00:00 UTC, obregonia1 commented on 05.ls/ls.rb
> +    file_names.map { |f| File.stat(f) }
改行必要ありませんでした。

2021-01-25 11:57 UTC, obregonia1 commented on 05.ls/ls.rb
> +  def initialize(type, permission, owner, group, time)
属性を5つに減らしました。

2021-01-25 11:58 UTC, obregonia1 commented on 05.ls/ls.rb
> +def main(files)
実行時の`main`メソッドを作成し、リファクタリングしました。

2021-01-25 12:02 UTC, obregonia1 commented on 05.ls/ls.rb
> +def display(files)
リファクタリングし、不要だったため「ファイル数が少ない場合とファイル名が長いファイルがない場合は一列に表示する」仕様を削除しました。
ちなみにこの仕様を残していたらrubocopに怒られました💦

2021-02-01 12:31 UTC, torinoko approved these changes
@obregonia1 
ちゃんと動いていることを確認しました 🙆‍♀️ 
がんばりましたね！お疲れ様でした！ 🍵

2021-02-01 12:31 UTC, torinoko commented on 05.ls/ls.rb
> +  (2 / rows[1]).times { file_names.push(nil) } unless (rows[1]).zero?
細かい話ですが
```
(rows[1]).zero?
```
はカッコなしで記述することが多いです。
```
rows[1].zero?
```
今回はこのままで全然問題ないです！！

2021-02-01 12:31 UTC, torinoko commented on 05.ls/ls.rb
> +def display(files)
Rubocop 厳しいですよね 😭

2021-02-01 13:11 UTC, obregonia1 commented on 05.ls/ls.rb
> +def display(files)
ですよね💦

2021-02-01 13:13 UTC, obregonia1 commented on 05.ls/ls.rb
> +  (2 / rows[1]).times { file_names.push(nil) } unless (rows[1]).zero?
カッコは必要ないですね！
気をつけます。

2021-02-02 02:56 UTC, merged